import type { Metadata } from "next";
import { IBM_Plex_Mono, IBM_Plex_Sans , Silkscreen } from "next/font/google";
import "./globals.css";

const geistSans = IBM_Plex_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = IBM_Plex_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: "400",
});

const silkScreen = Silkscreen({
  variable:"--font-silk-screen" , 
  subsets:["latin"]  ,
  weight :["400" , "700" ]  
})

export const metadata: Metadata = {
  title: "Ayushhh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${silkScreen.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
